sudo: required
dist: bionic
language: python
python:
    - "3.7"
addons:
  apt:
    sources:
    - sourceline: 'deb http://mirror2.openio.io/pub/repo/openio/sds/20.04/ubuntu/ bionic/'
      key_url: 'http://mirror2.openio.io/pub/repo/openio/APT-GPG-KEY-OPENIO-0'

env:
  matrix:
    - TEST_SUITE=iam SDS_BRANCH=master
#    - TEST_SUITE=s3 # Latest stable/supported versions
    - TEST_SUITE=s3 SDS_BRANCH=master # Integration with latest versions
    - TEST_SUITE=s3-basic SDS_BRANCH=master # Integration with latest versions
#    - TEST_SUITE=encryption
#    - TEST_SUITE=encryption SDS_BRANCH=master
#    - TEST_SUITE=swift
#    - TEST_SUITE=swift SDS_BRANCH=master
    - TEST_SUITE=unit
    - TEST_SUITE=unit SDS_BRANCH=master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes python-virtualenv jq liberasurecode-dev libssl-dev libattr1-dev libleveldb-dev libzookeeper-mt-dev

install:
  - gimme stable
  - source ~/.gimme/envs/latest.env
  - echo -en "travis_fold:start:install\r"
  - pip install --upgrade pip setuptools virtualenv tox flake8
  - test -n "$SDS_BRANCH" && git config --local submodule.oio-sds.branch "$SDS_BRANCH" || true
  - git submodule update --init --remote
  - ( grep -v -e "PyECLib" -e "requests" -e "six" third_party/oio-sds/all-requirements.txt ; grep -v -e "eventlet" -e "lxml" -e "oio" -e "xattr" requirements.txt ) | sort > deps-requirements.txt
  - pip install --upgrade -r deps-requirements.txt
  - cd third_party/oio-sds && python setup.py install && cd ../..
  - python setup.py develop
  - pip install --upgrade -r test-requirements.txt awscli nose-timer s3cmd
  - go get gopkg.in/ini.v1 golang.org/x/sys/unix
  - echo -en "travis_fold:end:install\r"

script:
  - source ~/.gimme/envs/latest.env
  - set -e
  - if [ "$TEST_SUITE" = "unit" ]; then flake8 oio_tests swift test; fi
  - if [ "$TEST_SUITE" = "unit" ]; then tox -e py37 test.unit.common.middleware.s3api; fi
  - ./oio_tests/run_tests.sh "$TEST_SUITE"
