version: v1.0
name: swift-tests-reports
jobs:
  - job: Collect coverage
    steps:

      - name: Checkout application
        checkout: '{{.cds.workspace}}'

      - name: Install dependencies
        script:
          - apt update
          - apt install -y python3-virtualenv virtualenv lcov
          - virtualenv -p /usr/bin/python3 $HOME/oiovenv
          - . $HOME/oiovenv/bin/activate
          - pip install --upgrade pip virtualenv coverage

      - artifactDownload:
          path: '{{.cds.workspace}}'
          pattern: 'coverage.*'
          tag: '{{.cds.version}}'

      - name: Aggregate coverage statistics
        script:
          - . $HOME/oiovenv/bin/activate
          - cd {{.cds.workspace}}
          - coverage combine
          - coverage report --skip-empty --ignore-errors > coverage-report-py.txt
          - worker upload --tag='{{.cds.version}}' {{.cds.workspace}}/coverage-report-py.txt
          - coverage xml --skip-empty --ignore-errors -o coverage-py.xml
          - mkdir coverage
          - coverage html --skip-empty --ignore-errors -d coverage/coverage-report-py
          - echo '<!DOCTYPE html><html><a href="./coverage-report-py/">Python coverage report</a></body></html>' > coverage/index.html

      - coverage:
          format: cobertura
          path: '{{.cds.workspace}}/coverage-py.xml'

      - artifactDownload:
          path: '{{.cds.workspace}}'
          pattern: 'tests_report.*.xml'
          tag: '{{.cds.version}}'

      - name: Filter tests reports
        script:
          - rm -f tests_report.ceph*.xml

      - jUnitReport: '{{.cds.workspace}}/tests_report.*.xml'

      - name: Publish code coverage reports on Artifactory
        optional: true
        OVH_Serve_Static_Files:
          destination: 'coverage/{{ .git.branch | replace "dev/" "develop/" | replace "feature/oio-backend" "master" | trunc 7 | replace "develop" "dev" }}/{{.cds.version}}'
          source: coverage
