version: v1.0
name: swift-build
jobs:
  - job: Compile package
    steps:
      - name: Checkout application
        checkout: '{{ .cds.workspace }}'
      - name: Clone external-packages
        script:
          - eval $(worker key install --env-git proj-ssh-openio)
          - git clone {{ .cds.proj.STASH_URL }}/openio/external-packages.git /external-packages
      - name: Build package and upload
        script: |+
          #!/bin/bash
          cat $0
          set -x
          export REPO_URL="https://{{ .cds.proj.drive_mirrors_objectstorage_openio_user }}:{{ .cds.proj.drive_mirrors_objectstorage_openio_password }}@{{ .cds.proj.drive_mirrors_hostname }}"
          make -f /external-packages/ubuntu/bionic/Makefile.common install-apt-repo
          # dev or prod release
          if [[ "{{ .git.tag }}" =~  ^[0-9]+\. ]]; then
            export VERSION={{ .git.tag }}
            export REPO_SUBREPO=main
            export REPO_LIMIT=0
          else
            export VERSION=$(date +%Y%m%d%H%M).git{{ .git.hash.short }}
            export REPO_SUBREPO=dev
            export REPO_LIMIT=100
          fi
          export PACKAGE=oio-swift

          make -f /external-packages/ubuntu/bionic/Makefile.common deb_changelog
          make -f /external-packages/ubuntu/bionic/Makefile.common
          make -f /external-packages/ubuntu/bionic/Makefile.common upload_to_repo
    requirements:
      - model: openio-debbuild-18.04
