version: v1.0
name: swift-build
jobs:
  - job: Compile ubuntu/20.04 package
    steps:
      - gitClone:
          branch: '{{ .git.branch }}'
          commit: '{{ .git.hash }}'
          depth: "false"
          directory: '{{ .cds.workspace }}'
          privateKey: proj-ssh-openio
          url: '{{ .git.url }}'

      - name: Clone external-packages
        script:
          - test -n "{{.cds.env.SDS_BRANCH}}" && git config --local submodule.oio-sds.branch "{{.cds.env.SDS_BRANCH}}" || true
          - eval $(worker key install --env-git proj-ssh-openio)
          - git submodule update --init --remote
          - git clone {{ .cds.proj.STASH_URL }}/openio/external-packages.git /external-packages

      - name: Build package and upload
        script: |+
          #!/bin/bash
          exec &> >(tee -a "package-20.04.log")
          trap 'worker upload --tag=focal package-20.04.log' EXIT
          cat $0
          set -x
          set -e
          # to be able to access other repositories from stash
          eval $(worker key install --env-git proj-ssh-openio)
          export REPO_URL="https://{{ .cds.proj.drive_mirrors_objectstorage_openio_user }}:{{ .cds.proj.drive_mirrors_objectstorage_openio_password }}@{{ .cds.proj.drive_mirrors_hostname }}"
          # dev or prod release
          PACKAGE=oio-swift
          export VERSION=1.0-focal
          export REPO_SUBREPO=main
          export REPO_LIMIT=0
          if [[ "{{ .git.tag }}" =~  ^[0-9]+\. ]]; then
            PACKAGE=${PACKAGE}-{{ .git.tag }}
          else
            PACKAGE=${PACKAGE}-$(date +%Y%m%d%H%M).git{{ .git.hash.short }}
          fi
          export PACKAGE=${PACKAGE}-ovh${CDS_VERSION}
          source .cds/versions
          make -f /external-packages/ubuntu/focal/Makefile.common install-apt-repo
          make -f /external-packages/ubuntu/focal/Makefile.common deb_changelog
          make -f /external-packages/ubuntu/focal/Makefile.common
          make -f /external-packages/ubuntu/focal/Makefile.common upload_to_artifacts
          make -f /external-packages/ubuntu/focal/Makefile.common upload_to_repo
    requirements:
      - model: openio-debbuild-20.04
