version: v.10
name: swift-oio-tests
jobs:
  - job: Run oio tests
    steps:

      - name: Checkout application
        checkout: '{{ .cds.workspace }}'

      - name: Install dependencies
        script: |+
          #!/bin/bash
          set -x
          . .cds/versions
          export DEBIAN_FRONTEND=noninteractive
          curl http://mirror2.openio.io/pub/repo/openio/APT-GPG-KEY-OPENIO-0 | apt-key add -
          apt-add-repository "deb http://mirror2.openio.io/pub/repo/openio/sds/20.04/ubuntu/ bionic/"
          apt-add-repository ppa:longsleep/golang-backports
          apt update
          # rabbitmq-server is not is the list as only necessary for oio-tests
          apt-get install -y rabbitmq-server $(tr '\n' ' ' < .cds/deps-ubuntu-bionic.txt)
          systemctl stop redis.service
          systemctl disable redis.service
          virtualenv -p /usr/bin/python3 $HOME/swiftenv
          cat << EOF > $HOME/swiftenv/pip.conf
          [global]
          index-url = https://${PYPI_SNAPSHOT}-pypi.snap.mirrors.ovh.net/simple/
          EOF
          . $HOME/swiftenv/bin/activate
          pip install --upgrade pip setuptools virtualenv tox -r test-requirements.txt
          test -n "{{.cds.env.SDS_BRANCH}}" && git config --local submodule.oio-sds.branch "{{.cds.env.SDS_BRANCH}}" || true
          eval $(worker key install --env-git proj-ssh-openio)
          git submodule update --init --remote
          cd third_party/oio-sds && pip install -e . && cd ../..
          pip install -e .
          ./third_party/oio-sds/tools/patch-python-modules.sh
          . ./oio_tests/functional/common.sh
          install_foundationdb "${FDB_VERSION}"
          rabbitmq-plugins enable rabbitmq_management

          echo "RateLimitBurst=0" >> /etc/systemd/journald.conf
          echo '$SystemLogRateLimitInterval 0' >> /etc/rsyslog.conf
          systemctl restart systemd-journald.service
          systemctl restart rsyslog.service

      - name: Run oio functional tests
        script:
          - pgrep rsyslogd || rsyslogd &
          - sysctl -w kernel.core_pattern='/tmp/core.%p.%E'
          - ulimit -c unlimited
          - ulimit -n 8192
          - . $HOME/swiftenv/bin/activate
          - ./oio_tests/run_tests.sh '{{.cds.env.TEST_SUITE}}'

      - name: Analyze Ceph S3 tests results
        script:
            - '[ "{{.cds.env.TEST_SUITE}}" = "ceph-s3tests" ] || exit 0'
            - . $HOME/swiftenv/bin/activate
            - ./third_party/ceph-s3tests-reports/bin/report.py --detailed ceph-s3tests-attributes.yaml --known-failures doc/s3api/conf/ceph-known-failures-oio.yaml tests_report.xml

      - name: Save coverage information
        always_executed: true
        script:
          - . $HOME/swiftenv/bin/activate
          - coverage combine
          - mv .coverage .coverage.oio.{{.cds.env.TEST_SUITE}}
          - worker upload --tag='{{.cds.version}}' '{{.cds.workspace}}/.coverage.oio.{{.cds.env.TEST_SUITE}}'

      - optional: true
        always_executed: true
        name: Save tests report
        script:
          - '[ "{{.cds.env.TEST_SUITE}}" = "ceph-s3tests" -a -f tests_report.xml ] && mv tests_report.xml "tests_report.ceph.s3tests.xml"'
          - '[ ! -f tests_report.xml ] || mv tests_report.xml "tests_report.oio.{{.cds.env.TEST_SUITE}}.xml"'
          - '[ ! -f tests_report.*.xml ] || worker upload --tag="{{.cds.version}}" tests_report.*.xml'

      - optional: true
        always_executed: true
        jUnitReport: '{{.cds.workspace}}/tests_report.*.xml'

    requirements:
      - model: Ubuntu-18.04-VM-b2-15
