version: v1.0
name: swift-build
jobs:
  - job: Compile ubuntu/18.04 package
    steps:
      - name: Checkout application
        checkout: '{{ .cds.workspace }}'

      - name: Clone external-packages
        script:
          - eval $(worker key install --env-git proj-ssh-openio)
          - git clone {{ .cds.proj.STASH_URL }}/openio/external-packages.git /external-packages

      - name: Build package and upload
        script: |+
          #!/bin/bash
          exec &> >(tee -a "package-18.04.log")
          trap 'worker upload --tag=bionic package-18.04.log' EXIT
          cat $0
          set -x
          # to be able to access other repositories from stash
          eval $(worker key install --env-git proj-ssh-openio)
          export REPO_URL="https://{{ .cds.proj.drive_mirrors_objectstorage_openio_user }}:{{ .cds.proj.drive_mirrors_objectstorage_openio_password }}@{{ .cds.proj.drive_mirrors_hostname }}"
          # dev or prod release
          PACKAGE=oio-swift
          export VERSION=1.0-bionic
          export REPO_SUBREPO=main
          export REPO_LIMIT=0
          if [[ "{{ .git.tag }}" =~  ^[0-9]+\. ]]; then
            PACKAGE=${PACKAGE}-{{ .git.tag }}
          else
            PACKAGE=${PACKAGE}-$(date +%Y%m%d%H%M).git{{ .git.hash.short }}
          fi
          export PACKAGE=${PACKAGE}-ovh${CDS_VERSION}

          make -f /external-packages/ubuntu/bionic/Makefile.common install-apt-repo
          make -f /external-packages/ubuntu/bionic/Makefile.common deb_changelog
          make -f /external-packages/ubuntu/bionic/Makefile.common
          make -f /external-packages/ubuntu/bionic/Makefile.common upload_to_artifacts
          make -f /external-packages/ubuntu/bionic/Makefile.common upload_to_repo
    requirements:
      - model: openio-debbuild-18.04

  - job: Compile ubuntu/20.04 package
    steps:
      - name: Checkout application
        checkout: '{{ .cds.workspace }}'

      - name: Clone external-packages
        script:
          - eval $(worker key install --env-git proj-ssh-openio)
          - git clone {{ .cds.proj.STASH_URL }}/openio/external-packages.git /external-packages

      - name: Build package and upload
        script: |+
          #!/bin/bash
          exec &> >(tee -a "package-20.04.log")
          trap 'worker upload --tag=focal package-20.04.log' EXIT
          cat $0
          set -x
          # to be able to access other repositories from stash
          eval $(worker key install --env-git proj-ssh-openio)
          export REPO_URL="https://{{ .cds.proj.drive_mirrors_objectstorage_openio_user }}:{{ .cds.proj.drive_mirrors_objectstorage_openio_password }}@{{ .cds.proj.drive_mirrors_hostname }}"
          # dev or prod release
          PACKAGE=oio-swift
          export VERSION=1.0-focal
          export REPO_SUBREPO=main
          export REPO_LIMIT=0
          if [[ "{{ .git.tag }}" =~  ^[0-9]+\. ]]; then
            PACKAGE=${PACKAGE}-{{ .git.tag }}
          else
            PACKAGE=${PACKAGE}-$(date +%Y%m%d%H%M).git{{ .git.hash.short }}
          fi
          export PACKAGE=${PACKAGE}-ovh${CDS_VERSION}

          make -f /external-packages/ubuntu/focal/Makefile.common install-apt-repo
          make -f /external-packages/ubuntu/focal/Makefile.common deb_changelog
          make -f /external-packages/ubuntu/focal/Makefile.common
          make -f /external-packages/ubuntu/focal/Makefile.common upload_to_artifacts
          make -f /external-packages/ubuntu/focal/Makefile.common upload_to_repo
    requirements:
      - model: openio-debbuild-20.04
