version: v1.0
name: swift-code-tests
jobs:
  - job: Run swift code quality tests
    steps:

      - name: Checkout application
        checkout: '{{ .cds.workspace }}'

      - name: Install dependencies
        script: |+
          #!/bin/bash
          set -x
          systemctl disable --now apt-daily.timer
          systemctl disable --now apt-daily-upgrade.timer
          . .cds/versions
          . .cds/configure-repositories.sh
          # We don't need Docker in this test workflow
          sed -i '/docker-compose-plugin/d' .cds/deps-ubuntu-focal.txt
          # Tox will be installed later with pip (to be able to control its version)
          sed -i '/tox/d' .cds/deps-ubuntu-focal.txt
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y $(tr '\n' ' ' < .cds/deps-ubuntu-focal.txt) ${PYTHON_PACKAGE} cargo-${RUST_VERSION}
          echo "export PATH=/opt/${PYTHON_PACKAGE}/bin:/usr/lib/rust-${RUST_VERSION}/bin:$PATH" > $HOME/swift-env.sh
          echo "export PIP_INDEX_URL=https://${PYPI_SNAPSHOT}-pypi.snap.mirrors.ovh.net/simple/" >> $HOME/swift-env.sh
          source $HOME/swift-env.sh
          /opt/${PYTHON_PACKAGE}/bin/python3 -m venv $HOME/swiftenv
          . $HOME/swiftenv/bin/activate
          pip install --progress-bar off --upgrade pip setuptools tox virtualenv
      - name: Run coding style tests
        script: |+
          #!/bin/bash
          set -x
          source $HOME/swift-env.sh
          . $HOME/swiftenv/bin/activate
          # No reason to no enable verbose mode (it helps to debug in case of failure)
          tox -e pep8 -v

    requirements:
        - model: Ubuntu-20.04-VM-b2-07
